// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bookingMessage.proto

package generatedEntities;

public final class Booking_Notif_OTA {
  private Booking_Notif_OTA() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Booking_NotifOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Booking_Notif)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string bookingID = 1;</code>
     */
    boolean hasBookingID();
    /**
     * <code>required string bookingID = 1;</code>
     */
    java.lang.String getBookingID();
    /**
     * <code>required string bookingID = 1;</code>
     */
    com.google.protobuf.ByteString
        getBookingIDBytes();

    /**
     * <code>required int32 customer_number = 2;</code>
     */
    boolean hasCustomerNumber();
    /**
     * <code>required int32 customer_number = 2;</code>
     */
    int getCustomerNumber();

    /**
     * <code>optional string checkinDate = 3;</code>
     */
    boolean hasCheckinDate();
    /**
     * <code>optional string checkinDate = 3;</code>
     */
    java.lang.String getCheckinDate();
    /**
     * <code>optional string checkinDate = 3;</code>
     */
    com.google.protobuf.ByteString
        getCheckinDateBytes();

    /**
     * <code>required string checkoutDate = 4;</code>
     */
    boolean hasCheckoutDate();
    /**
     * <code>required string checkoutDate = 4;</code>
     */
    java.lang.String getCheckoutDate();
    /**
     * <code>required string checkoutDate = 4;</code>
     */
    com.google.protobuf.ByteString
        getCheckoutDateBytes();

    /**
     * <code>required string customerName = 5;</code>
     */
    boolean hasCustomerName();
    /**
     * <code>required string customerName = 5;</code>
     */
    java.lang.String getCustomerName();
    /**
     * <code>required string customerName = 5;</code>
     */
    com.google.protobuf.ByteString
        getCustomerNameBytes();

    /**
     * <code>required int32 hotelId = 6;</code>
     */
    boolean hasHotelId();
    /**
     * <code>required int32 hotelId = 6;</code>
     */
    int getHotelId();

    /**
     * <code>required string paymentInstrumentId = 7;</code>
     */
    boolean hasPaymentInstrumentId();
    /**
     * <code>required string paymentInstrumentId = 7;</code>
     */
    java.lang.String getPaymentInstrumentId();
    /**
     * <code>required string paymentInstrumentId = 7;</code>
     */
    com.google.protobuf.ByteString
        getPaymentInstrumentIdBytes();

    /**
     * <code>required string phone = 8;</code>
     */
    boolean hasPhone();
    /**
     * <code>required string phone = 8;</code>
     */
    java.lang.String getPhone();
    /**
     * <code>required string phone = 8;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();
  }
  /**
   * Protobuf type {@code tutorial.Booking_Notif}
   */
  public static final class Booking_Notif extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.Booking_Notif)
      Booking_NotifOrBuilder {
    // Use Booking_Notif.newBuilder() to construct.
    private Booking_Notif(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Booking_Notif(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Booking_Notif defaultInstance;
    public static Booking_Notif getDefaultInstance() {
      return defaultInstance;
    }

    public Booking_Notif getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Booking_Notif(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      //int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              bookingID_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              customerNumber_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              checkinDate_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              checkoutDate_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              customerName_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              hotelId_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              paymentInstrumentId_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              phone_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generatedEntities.Booking_Notif_OTA.internal_static_tutorial_Booking_Notif_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generatedEntities.Booking_Notif_OTA.internal_static_tutorial_Booking_Notif_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generatedEntities.Booking_Notif_OTA.Booking_Notif.class, generatedEntities.Booking_Notif_OTA.Booking_Notif.Builder.class);
    }

    public static com.google.protobuf.Parser<Booking_Notif> PARSER =
        new com.google.protobuf.AbstractParser<Booking_Notif>() {
      public Booking_Notif parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Booking_Notif(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Booking_Notif> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BOOKINGID_FIELD_NUMBER = 1;
    private java.lang.Object bookingID_;
    /**
     * <code>required string bookingID = 1;</code>
     */
    public boolean hasBookingID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string bookingID = 1;</code>
     */
    public java.lang.String getBookingID() {
      java.lang.Object ref = bookingID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bookingID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string bookingID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBookingIDBytes() {
      java.lang.Object ref = bookingID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookingID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMER_NUMBER_FIELD_NUMBER = 2;
    private int customerNumber_;
    /**
     * <code>required int32 customer_number = 2;</code>
     */
    public boolean hasCustomerNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 customer_number = 2;</code>
     */
    public int getCustomerNumber() {
      return customerNumber_;
    }

    public static final int CHECKINDATE_FIELD_NUMBER = 3;
    private java.lang.Object checkinDate_;
    /**
     * <code>optional string checkinDate = 3;</code>
     */
    public boolean hasCheckinDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string checkinDate = 3;</code>
     */
    public java.lang.String getCheckinDate() {
      java.lang.Object ref = checkinDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          checkinDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string checkinDate = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCheckinDateBytes() {
      java.lang.Object ref = checkinDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checkinDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHECKOUTDATE_FIELD_NUMBER = 4;
    private java.lang.Object checkoutDate_;
    /**
     * <code>required string checkoutDate = 4;</code>
     */
    public boolean hasCheckoutDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string checkoutDate = 4;</code>
     */
    public java.lang.String getCheckoutDate() {
      java.lang.Object ref = checkoutDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          checkoutDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string checkoutDate = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCheckoutDateBytes() {
      java.lang.Object ref = checkoutDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checkoutDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMERNAME_FIELD_NUMBER = 5;
    private java.lang.Object customerName_;
    /**
     * <code>required string customerName = 5;</code>
     */
    public boolean hasCustomerName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string customerName = 5;</code>
     */
    public java.lang.String getCustomerName() {
      java.lang.Object ref = customerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          customerName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string customerName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCustomerNameBytes() {
      java.lang.Object ref = customerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOTELID_FIELD_NUMBER = 6;
    private int hotelId_;
    /**
     * <code>required int32 hotelId = 6;</code>
     */
    public boolean hasHotelId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 hotelId = 6;</code>
     */
    public int getHotelId() {
      return hotelId_;
    }

    public static final int PAYMENTINSTRUMENTID_FIELD_NUMBER = 7;
    private java.lang.Object paymentInstrumentId_;
    /**
     * <code>required string paymentInstrumentId = 7;</code>
     */
    public boolean hasPaymentInstrumentId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string paymentInstrumentId = 7;</code>
     */
    public java.lang.String getPaymentInstrumentId() {
      java.lang.Object ref = paymentInstrumentId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          paymentInstrumentId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string paymentInstrumentId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPaymentInstrumentIdBytes() {
      java.lang.Object ref = paymentInstrumentId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paymentInstrumentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 8;
    private java.lang.Object phone_;
    /**
     * <code>required string phone = 8;</code>
     */
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string phone = 8;</code>
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          phone_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string phone = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      bookingID_ = "";
      customerNumber_ = 0;
      checkinDate_ = "";
      checkoutDate_ = "";
      customerName_ = "";
      hotelId_ = 0;
      paymentInstrumentId_ = "";
      phone_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBookingID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCustomerNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCheckoutDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCustomerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHotelId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPaymentInstrumentId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPhone()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBookingIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, customerNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCheckinDateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCheckoutDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getCustomerNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, hotelId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getPaymentInstrumentIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getPhoneBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBookingIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, customerNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCheckinDateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCheckoutDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getCustomerNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, hotelId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getPaymentInstrumentIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getPhoneBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static generatedEntities.Booking_Notif_OTA.Booking_Notif parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedEntities.Booking_Notif_OTA.Booking_Notif parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedEntities.Booking_Notif_OTA.Booking_Notif parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedEntities.Booking_Notif_OTA.Booking_Notif parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedEntities.Booking_Notif_OTA.Booking_Notif parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static generatedEntities.Booking_Notif_OTA.Booking_Notif parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static generatedEntities.Booking_Notif_OTA.Booking_Notif parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static generatedEntities.Booking_Notif_OTA.Booking_Notif parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static generatedEntities.Booking_Notif_OTA.Booking_Notif parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static generatedEntities.Booking_Notif_OTA.Booking_Notif parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(generatedEntities.Booking_Notif_OTA.Booking_Notif prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Booking_Notif}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Booking_Notif)
        generatedEntities.Booking_Notif_OTA.Booking_NotifOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return generatedEntities.Booking_Notif_OTA.internal_static_tutorial_Booking_Notif_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return generatedEntities.Booking_Notif_OTA.internal_static_tutorial_Booking_Notif_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                generatedEntities.Booking_Notif_OTA.Booking_Notif.class, generatedEntities.Booking_Notif_OTA.Booking_Notif.Builder.class);
      }

      // Construct using generatedEntities.Booking_Notif_OTA.Booking_Notif.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bookingID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        customerNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        checkinDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        checkoutDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        customerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        hotelId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        paymentInstrumentId_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        phone_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return generatedEntities.Booking_Notif_OTA.internal_static_tutorial_Booking_Notif_descriptor;
      }

      public generatedEntities.Booking_Notif_OTA.Booking_Notif getDefaultInstanceForType() {
        return generatedEntities.Booking_Notif_OTA.Booking_Notif.getDefaultInstance();
      }

      public generatedEntities.Booking_Notif_OTA.Booking_Notif build() {
        generatedEntities.Booking_Notif_OTA.Booking_Notif result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public generatedEntities.Booking_Notif_OTA.Booking_Notif buildPartial() {
        generatedEntities.Booking_Notif_OTA.Booking_Notif result = new generatedEntities.Booking_Notif_OTA.Booking_Notif(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bookingID_ = bookingID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.customerNumber_ = customerNumber_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.checkinDate_ = checkinDate_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.checkoutDate_ = checkoutDate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.customerName_ = customerName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.hotelId_ = hotelId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.paymentInstrumentId_ = paymentInstrumentId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.phone_ = phone_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof generatedEntities.Booking_Notif_OTA.Booking_Notif) {
          return mergeFrom((generatedEntities.Booking_Notif_OTA.Booking_Notif)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(generatedEntities.Booking_Notif_OTA.Booking_Notif other) {
        if (other == generatedEntities.Booking_Notif_OTA.Booking_Notif.getDefaultInstance()) return this;
        if (other.hasBookingID()) {
          bitField0_ |= 0x00000001;
          bookingID_ = other.bookingID_;
          onChanged();
        }
        if (other.hasCustomerNumber()) {
          setCustomerNumber(other.getCustomerNumber());
        }
        if (other.hasCheckinDate()) {
          bitField0_ |= 0x00000004;
          checkinDate_ = other.checkinDate_;
          onChanged();
        }
        if (other.hasCheckoutDate()) {
          bitField0_ |= 0x00000008;
          checkoutDate_ = other.checkoutDate_;
          onChanged();
        }
        if (other.hasCustomerName()) {
          bitField0_ |= 0x00000010;
          customerName_ = other.customerName_;
          onChanged();
        }
        if (other.hasHotelId()) {
          setHotelId(other.getHotelId());
        }
        if (other.hasPaymentInstrumentId()) {
          bitField0_ |= 0x00000040;
          paymentInstrumentId_ = other.paymentInstrumentId_;
          onChanged();
        }
        if (other.hasPhone()) {
          bitField0_ |= 0x00000080;
          phone_ = other.phone_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBookingID()) {
          
          return false;
        }
        if (!hasCustomerNumber()) {
          
          return false;
        }
        if (!hasCheckoutDate()) {
          
          return false;
        }
        if (!hasCustomerName()) {
          
          return false;
        }
        if (!hasHotelId()) {
          
          return false;
        }
        if (!hasPaymentInstrumentId()) {
          
          return false;
        }
        if (!hasPhone()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        generatedEntities.Booking_Notif_OTA.Booking_Notif parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (generatedEntities.Booking_Notif_OTA.Booking_Notif) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object bookingID_ = "";
      /**
       * <code>required string bookingID = 1;</code>
       */
      public boolean hasBookingID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string bookingID = 1;</code>
       */
      public java.lang.String getBookingID() {
        java.lang.Object ref = bookingID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bookingID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string bookingID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBookingIDBytes() {
        java.lang.Object ref = bookingID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bookingID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string bookingID = 1;</code>
       */
      public Builder setBookingID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bookingID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string bookingID = 1;</code>
       */
      public Builder clearBookingID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bookingID_ = getDefaultInstance().getBookingID();
        onChanged();
        return this;
      }
      /**
       * <code>required string bookingID = 1;</code>
       */
      public Builder setBookingIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bookingID_ = value;
        onChanged();
        return this;
      }

      private int customerNumber_ ;
      /**
       * <code>required int32 customer_number = 2;</code>
       */
      public boolean hasCustomerNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 customer_number = 2;</code>
       */
      public int getCustomerNumber() {
        return customerNumber_;
      }
      /**
       * <code>required int32 customer_number = 2;</code>
       */
      public Builder setCustomerNumber(int value) {
        bitField0_ |= 0x00000002;
        customerNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 customer_number = 2;</code>
       */
      public Builder clearCustomerNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        customerNumber_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object checkinDate_ = "";
      /**
       * <code>optional string checkinDate = 3;</code>
       */
      public boolean hasCheckinDate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string checkinDate = 3;</code>
       */
      public java.lang.String getCheckinDate() {
        java.lang.Object ref = checkinDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            checkinDate_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string checkinDate = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCheckinDateBytes() {
        java.lang.Object ref = checkinDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          checkinDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string checkinDate = 3;</code>
       */
      public Builder setCheckinDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        checkinDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string checkinDate = 3;</code>
       */
      public Builder clearCheckinDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        checkinDate_ = getDefaultInstance().getCheckinDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string checkinDate = 3;</code>
       */
      public Builder setCheckinDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        checkinDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object checkoutDate_ = "";
      /**
       * <code>required string checkoutDate = 4;</code>
       */
      public boolean hasCheckoutDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string checkoutDate = 4;</code>
       */
      public java.lang.String getCheckoutDate() {
        java.lang.Object ref = checkoutDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            checkoutDate_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string checkoutDate = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCheckoutDateBytes() {
        java.lang.Object ref = checkoutDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          checkoutDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string checkoutDate = 4;</code>
       */
      public Builder setCheckoutDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        checkoutDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string checkoutDate = 4;</code>
       */
      public Builder clearCheckoutDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        checkoutDate_ = getDefaultInstance().getCheckoutDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string checkoutDate = 4;</code>
       */
      public Builder setCheckoutDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        checkoutDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object customerName_ = "";
      /**
       * <code>required string customerName = 5;</code>
       */
      public boolean hasCustomerName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string customerName = 5;</code>
       */
      public java.lang.String getCustomerName() {
        java.lang.Object ref = customerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            customerName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string customerName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCustomerNameBytes() {
        java.lang.Object ref = customerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string customerName = 5;</code>
       */
      public Builder setCustomerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        customerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string customerName = 5;</code>
       */
      public Builder clearCustomerName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        customerName_ = getDefaultInstance().getCustomerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string customerName = 5;</code>
       */
      public Builder setCustomerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        customerName_ = value;
        onChanged();
        return this;
      }

      private int hotelId_ ;
      /**
       * <code>required int32 hotelId = 6;</code>
       */
      public boolean hasHotelId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 hotelId = 6;</code>
       */
      public int getHotelId() {
        return hotelId_;
      }
      /**
       * <code>required int32 hotelId = 6;</code>
       */
      public Builder setHotelId(int value) {
        bitField0_ |= 0x00000020;
        hotelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 hotelId = 6;</code>
       */
      public Builder clearHotelId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        hotelId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object paymentInstrumentId_ = "";
      /**
       * <code>required string paymentInstrumentId = 7;</code>
       */
      public boolean hasPaymentInstrumentId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string paymentInstrumentId = 7;</code>
       */
      public java.lang.String getPaymentInstrumentId() {
        java.lang.Object ref = paymentInstrumentId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            paymentInstrumentId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string paymentInstrumentId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPaymentInstrumentIdBytes() {
        java.lang.Object ref = paymentInstrumentId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          paymentInstrumentId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string paymentInstrumentId = 7;</code>
       */
      public Builder setPaymentInstrumentId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        paymentInstrumentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string paymentInstrumentId = 7;</code>
       */
      public Builder clearPaymentInstrumentId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        paymentInstrumentId_ = getDefaultInstance().getPaymentInstrumentId();
        onChanged();
        return this;
      }
      /**
       * <code>required string paymentInstrumentId = 7;</code>
       */
      public Builder setPaymentInstrumentIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        paymentInstrumentId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phone_ = "";
      /**
       * <code>required string phone = 8;</code>
       */
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string phone = 8;</code>
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            phone_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string phone = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string phone = 8;</code>
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string phone = 8;</code>
       */
      public Builder clearPhone() {
        bitField0_ = (bitField0_ & ~0x00000080);
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>required string phone = 8;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        phone_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Booking_Notif)
    }

    static {
      defaultInstance = new Booking_Notif(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.Booking_Notif)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Booking_Notif_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Booking_Notif_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024bookingMessage.proto\022\010tutorial\"\271\001\n\rBoo" +
      "king_Notif\022\021\n\tbookingID\030\001 \002(\t\022\027\n\017custome" +
      "r_number\030\002 \002(\005\022\023\n\013checkinDate\030\003 \001(\t\022\024\n\014c" +
      "heckoutDate\030\004 \002(\t\022\024\n\014customerName\030\005 \002(\t\022" +
      "\017\n\007hotelId\030\006 \002(\005\022\033\n\023paymentInstrumentId\030" +
      "\007 \002(\t\022\r\n\005phone\030\010 \002(\tB&\n\021generatedEntitie" +
      "sB\021Booking_Notif_OTA"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_Booking_Notif_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Booking_Notif_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_Booking_Notif_descriptor,
        new java.lang.String[] { "BookingID", "CustomerNumber", "CheckinDate", "CheckoutDate", "CustomerName", "HotelId", "PaymentInstrumentId", "Phone", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
